name: Clean old workflow runs
on:
  workflow_dispatch:
  # Run at 01:00 every six days.
  schedule:
    - cron: '0 1 */6 * *'

jobs:
  del_runs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ['cache.yml', 'clean.yml']
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: ${{ matrix.file }}
          retain_days: 1
          keep_minimum_runs: 1
